let cards=[];const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0);
function toast(message){$('toast').textContent=message;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3000)}async function api(path,opt={}){const r=await fetch(path,{credentials:'include',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}}),d=await r.json().catch(()=>({message:'Invalid server response'}));if(r.status===401){location.href='/';throw Error('Please sign in again.')}if(!r.ok||!d.success)throw Error(d.message||'Request failed');return d}function logout(){location.href='/logout'}
document.querySelectorAll('.tabs button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));button.classList.add('active');$(button.dataset.tab).classList.add('active')});
async function loadUser(){try{const d=await api('/api/me'),u=d.user;$('customer-name').textContent=u.name;$('customer-account').textContent='•••• '+String(u.accountNumber).slice(-4);$('avatar').textContent=u.name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}catch(e){}}
function cardVisual(c){return `<article class="bank-card ${esc(c.card_type)}"><div class="chip"></div><span class="status">${esc(c.status)}</span><div class="number">${esc(c.card_number_masked||'XXXX XXXX XXXX ----')}</div><div class="row"><div><small>CARDHOLDER</small><b>${esc(c.cardholder_name||'SPX CUSTOMER')}</b></div><div><small>TYPE</small><b>${esc(c.variant)} ${esc(c.card_type)}</b></div></div></article>`}
function manageRow(c){const action=c.status==='BLOCKED'?'UNBLOCK':'BLOCK',enabled=['ACTIVE','ISSUED','BLOCKED'].includes(c.status);return `<article class="manage-row"><div><h3>${esc(c.variant)} ${esc(c.card_type)} · ${esc(c.card_number_masked||'Pending issuance')}</h3><p>Requested ${new Date(c.created_at).toLocaleDateString('en-IN')} · Status: <b>${esc(c.status)}</b></p></div><div class="actions">${enabled?`<button class="${action==='BLOCK'?'danger':''}" onclick="changeStatus(${c.id},'${action}')">${action==='BLOCK'?'Temporarily block':'Unblock card'}</button>`:'<span class="status">Awaiting admin approval</span>'}</div></article>`}
function controlRow(c){if(!['ACTIVE','ISSUED','BLOCKED'].includes(c.status))return manageRow(c);return `<article class="manage-row controls-card"><h3>${esc(c.variant)} ${esc(c.card_type)} · ${esc(c.card_number_masked)}</h3><div class="control-grid"><label>Daily ATM limit<input id="atm-${c.id}" type="number" min="1" max="100000" value="${c.daily_atm_limit}"></label><label>Daily purchase limit<input id="pos-${c.id}" type="number" min="1" max="500000" value="${c.daily_pos_limit}"></label></div><div class="switches"><label><input id="online-${c.id}" type="checkbox" ${c.online_enabled?'checked':''}> Online transactions</label><label><input id="intl-${c.id}" type="checkbox" ${c.international_enabled?'checked':''}> International usage</label><label><input id="tap-${c.id}" type="checkbox" ${c.contactless_enabled?'checked':''}> Contactless payments</label></div><button class="primary" onclick="saveControls(${c.id})">Save controls</button></article>`}
async function loadCards(){try{const d=await api('/api/cards');cards=d.cards;$('card-grid').innerHTML=cards.length?cards.map(cardVisual).join(''):'<div class="empty">No card requests yet. Choose a debit or credit application tab to begin.</div>';for(const type of ['DEBIT','CREDIT']){$(type.toLowerCase()+'-list').innerHTML=cards.filter(c=>c.card_type===type).map(manageRow).join('')||'<div class="empty">No '+type.toLowerCase()+' card records.</div>'}$('controls-list').innerHTML=cards.map(controlRow).join('')||'<div class="empty">No cards available for controls.</div>'}catch(e){toast(e.message)}}
async function submitRequest(event,type){event.preventDefault();const form=event.target,payload={card_type:type,variant:form.variant.value,delivery_address:form.address.value};if(type==='CREDIT')payload.requested_limit=Number(form.limit.value);try{const d=await api('/api/cards',{method:'POST',body:JSON.stringify(payload)});toast(d.message);form.reset();await loadCards();document.querySelector('[data-tab="overview"]').click()}catch(e){toast(e.message)}}
async function changeStatus(id,action){if(!confirm(`${action==='BLOCK'?'Block':'Unblock'} this card?`))return;try{const d=await api(`/api/cards/${id}/status`,{method:'PATCH',body:JSON.stringify({action})});toast(d.message);loadCards()}catch(e){toast(e.message)}}
async function saveControls(id){try{const payload={daily_atm_limit:Number($(`atm-${id}`).value),daily_pos_limit:Number($(`pos-${id}`).value),online_enabled:$(`online-${id}`).checked,international_enabled:$(`intl-${id}`).checked,contactless_enabled:$(`tap-${id}`).checked};const d=await api(`/api/cards/${id}/controls`,{method:'PATCH',body:JSON.stringify(payload)});toast(d.message);loadCards()}catch(e){toast(e.message)}}
document.addEventListener('DOMContentLoaded',()=>{loadUser();loadCards()});
